@startuml

class Money <<ValueObject>>
{
    -Amount : int
    +Currency : string
    #Money(int amount, string currency)
    Times(int amount) : Money
    
    {static} Dollar(int amount) : Money
    {static} Franc(int amount) : Money
}
@enduml